---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: "{{ item }}"
  with_first_found:
     - "{{ ansible_distribution }}.yml"
     - "{{ ansible_os_family }}.yml"

- name: Set configuration
  template:
    src: "{{ influxdb_conf_template }}"
    dest: "{{ influxdb_conf_path }}"
    owner: root
    group: root
    mode:  0644

- name: 'Restart service'
  service:
    name: "{{ influxdb_service_name }}"
    state: restarted
    enabled: true

- name: Configure service
  include_tasks: "configure.yml"
